

INSERT INTO Lieu VALUES (1, 'SALLE DU PANIER FLEURI', 'Rue de Bonneville', 450);
INSERT INTO Lieu VALUES (2, 'LE CABARET', 'MAIRIE ANNEXE DE PARAME, Place Georges COUDRAY', 250);
INSERT INTO Lieu VALUES (3, 'LE PARC DES CHENES', '14 rue des chênes', 2000);
INSERT INTO Lieu VALUES (4, 'LE VILLAGE', 'Ecole LEGATELOIS, 25 rue Général de Castelnau', 500);